export const data = [
  {
    img: require("../assets/usb1.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 12,
    price: "69.900 đ",
    disCount: "-39%",
  },
  {
    img: require("../assets/usb2.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 24,
    price: "99.900 đ",
    disCount: "-79%",
  },
  {
    img: require("../assets/usb3.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 98,
    price: "39.900 đ",
    disCount: "-34%",
  },
  {
    img: require("../assets/usb4.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 302,
    price: "692.900 đ",
    disCount: "-29%",
  },
  {
    img: require("../assets/usb5.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 123,
    price: "234.900 đ",
    disCount: "-53%",
  },
  {
    img: require("../assets/usb6.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 122,
    price: "765.900 đ",
    disCount: "-19%",
  },
  {
    img: require("../assets/usb1.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 12,
    price: "69.900 đ",
    disCount: "-39%",
  },
  {
    img: require("../assets/usb2.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 24,
    price: "99.900 đ",
    disCount: "-79%",
  },
  {
    img: require("../assets/usb3.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 98,
    price: "39.900 đ",
    disCount: "-34%",
  },
  {
    img: require("../assets/usb4.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 302,
    price: "692.900 đ",
    disCount: "-29%",
  },
  {
    img: require("../assets/usb5.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 123,
    price: "234.900 đ",
    disCount: "-53%",
  },
  {
    img: require("../assets/usb6.png"),
    content: "Cáp chuyển từ Cổng USB sang PS2...",
    imgRating: require("../assets/rating.png"),
    review: 122,
    price: "765.900 đ",
    disCount: "-19%",
  },
];
